//-
// Copyright 2017, 2018 The proptest developers
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

use crate::std_facade::fmt;
use crate::test_runner::{Reason, TestRng};

//==============================================================================
// Traits
//==============================================================================

/// A new [`ValueTree`] from a [`Strategy`] when [`Ok`] or otherwise [`Err`]
/// when a new value-tree can not be produced for some reason such as
/// in the case of filtering with a predicate which always returns false.
/// You should pass in your strategy as the type parameter.
///
/// [`Strategy`]: trait.Strategy.html
/// [`ValueTree`]: trait.ValueTree.html
/// [`Ok`]: https://doc.rust-lang.org/nightly/std/result/enum.Result.html#variant.Ok
/// [`Err`]: https://doc.rust-lang.org/nightly/std/result/enum.Result.html#variant.Err
pub type NewTree<S> = Result<<S as Strategy>::Tree, Reason>;

/// A strategy for producing arbitrary values of a given type.
///
/// This is the core trait of proptest. A `Strategy` is responsible for both
/// generating random values and "shrinking" them to simpler values when a test
/// fails.
///
/// Shrinking is performed through the associated `ValueTree` type. A `Strategy`
/// doesn't directly produce values; instead, it produces a `ValueTree`, which
/// represents a starting value and knows how to simplify itself.
///
/// `fmt::Debug` is a hard requirement for all strategies currently due to
/// `prop_flat_map()`. This constraint will be removed when specialisation
/// becomes stable.
#[must_use = "strategies do nothing unless used"]
pub trait Strategy: fmt::Debug {
    /// The value tree generated by this `Strategy`.
    type Tree: ValueTree<Value = Self::Value>;

    /// The type of value used by functions under test generated by this Strategy.
    ///
    /// This corresponds to the same type as the associated type `Value`
    /// in `Self::Tree`. It is provided here to simplify usage particularly
    /// in conjunction with `-> impl Strategy<Value = MyType>`.
    type Value: fmt::Debug;

    /// Generate a new value tree from the given random number generator.
    ///
    /// This may fail if there are constraints on the generated value and the
    /// generator is unable to produce anything that satisfies them. Any
    /// failure is wrapped in `Reason`.
    ///
    /// This method is generally expected to be deterministic. That is, given a
    /// `TestRng` in a particular state, this should produce an identical
    /// `ValueTree` every time. Non-deterministic strategies do not cause
    /// problems during normal operation, but they do break failure persistence
    /// since it is implemented by simply saving the seed used to generate the
    /// test case.
    fn new_tree(&self, runner: &mut TestRng) -> NewTree<Self>;
}

/// A value tree represents a single generated value and a number of
/// simplifications that can be applied to it.
///
/// The tree metaphor comes from the fact that the root of the tree is the
/// original generated value, and each simplification is a child. In proptest,
/// trees are explored by starting at the root, then repeatedly attempting to
/// simplify to children. When a child is found that preserves the property
/// that caused the test to fail, it becomes the new root, and the process
/// repeats.
///
/// The `ValueTree` trait provides the interface for this search. The `current()`
/// method returns the value at the current node. The `simplify()` method
/// attempts to move to a simpler child node, returning `false` when no more
/// simplification is possible. The `complicate()` method backs up from a
/// failed simplification attempt.
///
/// ## Implementing `ValueTree`
///
/// The most common implementation strategy is to track "low" and "high" bounds
/// that represent the range of possible simplifications. The `current()` value
/// starts at "high". When `simplify()` is called, the implementation sets
/// "high" to the current value and moves the current value to the midpoint
/// between "low" and "high" (rounding toward "low"). When `complicate()` is
/// called, the implementation sets "low" to the current value plus one and
/// moves the current value to the midpoint between the new "low" and "high".
///
/// This approach ensures that the search converges toward the smallest value
/// that still causes the test to fail, which is the "minimal failing input".
pub trait ValueTree {
    /// The type of the value produced by this `ValueTree`.
    type Value: fmt::Debug;

    /// Returns the current value.
    fn current(&self) -> Self::Value;

    /// Attempts to simplify the current value. Notionally, this sets the
    /// "high" value to the current value, and the current value to a "halfway
    /// point" between high and low, rounding towards low.
    ///
    /// Returns whether any state changed as a result of this call. This does
    /// not necessarily imply that the value of `current()` has changed, since
    /// in the most general case, it is not possible for an implementation to
    /// determine this.
    ///
    /// This call needs to correctly handle being called even immediately after
    /// it had been called previously and returned `false`.
    fn simplify(&mut self) -> bool;

    /// Attempts to partially undo the last simplification. Notionally, this
    /// sets the "low" value to one plus the current value, and the current
    /// value to a "halfway point" between high and the new low, rounding
    /// towards low.
    ///
    /// Returns whether any state changed as a result of this call. This does
    /// not necessarily imply that the value of `current()` has changed, since
    /// in the most general case, it is not possible for an implementation to
    /// determine this.
    ///
    /// It is usually expected that, immediately after a call to `simplify()`
    /// which returns true, this call will itself return true. However, this is
    /// not always the case; in some strategies, particularly those that use
    /// some form of rejection sampling, the act of trying to simplify may
    /// change the state such that `simplify()` returns true, yet ultimately
    /// left the resulting value unchanged, in which case there is nothing left
    /// to complicate.
    ///
    /// This call does not need to gracefully handle being called before
    /// `simplify()` was ever called, but does need to correctly handle being
    /// called even immediately after it had been called previously and
    /// returned `false`.
    fn complicate(&mut self) -> bool;
}
